using Soundstage.Core.Configio;
using Soundstage.Core.Tests.Support;
using Xunit;

namespace Soundstage.Core.Tests.Configio;

public class TakeoverServiceTests
{
    private readonly InMemoryFileSystem _fs = new();
    private readonly TestClock _clock = new();
    private readonly ConfigLayout _layout = new(@"C:\config");
    private readonly TakeoverService _service;
    private readonly BackupService _backups;

    public TakeoverServiceTests()
    {
        _backups = new BackupService(_fs, _layout, _clock);
        _service = new TakeoverService(_fs, _layout, _backups);
    }

    [Theory]
    [InlineData(null, ExistingConfigKind.Missing)]
    [InlineData("# Default config file for Equalizer APO\r\nPreamp: -6 dB\r\nInclude: example.txt\r\n", ExistingConfigKind.StockDefault)]
    [InlineData("Include: peace.txt\r\n", ExistingConfigKind.Peace)]
    [InlineData("# Generated by PEACE equalizer\r\nPreamp: -3 dB\r\n", ExistingConfigKind.Peace)]
    [InlineData("Preamp: -2 dB\r\nFilter 1: ON PK Fc 40 Hz Gain 4 dB Q 1\r\n", ExistingConfigKind.Custom)]
    public void Classify_RecognizesConfigOrigins(string? content, ExistingConfigKind expected)
    {
        Assert.Equal(expected, TakeoverService.Classify(content));
    }

    [Fact]
    public void MissingConfig_TakeOwnership_WritesEverything_NoBackup()
    {
        Assert.Equal(OwnershipState.MissingConfig, _service.GetOwnershipState());

        var report = _service.TakeOwnership();

        Assert.True(report.TookOwnership);
        Assert.Null(report.OriginalBackupPath);
        Assert.Equal(_layout.BuildStubContent(), _fs.ReadAllText(_layout.ConfigTxtPath));
        Assert.True(_fs.FileExists(_layout.UserFilePath));
        Assert.True(_fs.FileExists(_layout.ChainFilePath));
        Assert.True(_fs.FileExists(_layout.SwitchFilePath));
        Assert.Equal(OwnershipState.Owned, _service.GetOwnershipState());
    }

    [Fact]
    public void ForeignConfig_IsBackedUp_BeforeStubReplacesIt()
    {
        const string peaceConfig = "Include: peace.txt\r\n";
        _fs.WriteAllTextAtomic(_layout.ConfigTxtPath, peaceConfig);

        var report = _service.TakeOwnership();

        Assert.True(report.TookOwnership);
        Assert.Equal(ExistingConfigKind.Peace, report.PreviousKind);
        Assert.NotNull(report.OriginalBackupPath);
        Assert.Equal(peaceConfig, _fs.ReadAllText(report.OriginalBackupPath));
        Assert.Equal(_layout.BuildStubContent(), _fs.ReadAllText(_layout.ConfigTxtPath));
    }

    [Fact]
    public void TakeOwnership_IsIdempotent_NoDuplicateBackupsOrWrites()
    {
        _service.TakeOwnership();
        var writesAfterFirst = _fs.WriteLog.Count;

        var second = _service.TakeOwnership();

        Assert.False(second.TookOwnership);
        Assert.Equal(writesAfterFirst, _fs.WriteLog.Count);
        Assert.Empty(_backups.List());
    }

    [Fact]
    public void UserFile_IsNeverOverwritten_OnRetake()
    {
        _service.TakeOwnership();
        _fs.WriteAllTextAtomic(_layout.UserFilePath, "# my precious custom lines\r\n");

        // Someone (Peace) steals config.txt; we re-take.
        _fs.WriteAllTextAtomic(_layout.ConfigTxtPath, "Include: peace.txt\r\n");
        Assert.Equal(OwnershipState.NotOwned, _service.GetOwnershipState());
        _service.TakeOwnership();

        Assert.Equal("# my precious custom lines\r\n", _fs.ReadAllText(_layout.UserFilePath));
    }

    [Fact]
    public void HandEditedStub_IsDetected_AsOwnedButModified_AndBackedUpOnRetake()
    {
        _service.TakeOwnership();
        var tampered = _fs.ReadAllText(_layout.ConfigTxtPath) + "Preamp: -3 dB\r\n";
        _fs.WriteAllTextAtomic(_layout.ConfigTxtPath, tampered);

        Assert.Equal(OwnershipState.OwnedButModified, _service.GetOwnershipState());

        var report = _service.TakeOwnership();
        Assert.True(report.TookOwnership);
        Assert.NotNull(report.OriginalBackupPath);
        Assert.Equal(tampered, _fs.ReadAllText(report.OriginalBackupPath));
    }

    [Fact]
    public void Disown_RestoresNewestOriginalBackup()
    {
        _fs.WriteAllTextAtomic(_layout.ConfigTxtPath, "my hand written config\r\n");
        _service.TakeOwnership();

        _service.Disown();

        Assert.Equal("my hand written config\r\n", _fs.ReadAllText(_layout.ConfigTxtPath));
        // Managed directory (and its backups) remain for a later re-install.
        Assert.True(_fs.FileExists(_layout.ChainFilePath));
    }

    [Fact]
    public void Disown_WithoutBackup_WritesStockDefault()
    {
        _service.TakeOwnership();
        _service.Disown();

        var restored = _fs.ReadAllText(_layout.ConfigTxtPath);
        Assert.Contains("Preamp: -6 dB", restored);
        Assert.Equal(ExistingConfigKind.StockDefault, TakeoverService.Classify(restored));
    }
}
