using Soundstage.Core.Apo;

namespace Soundstage.Core.Configio;

/// <summary>
/// The on-disk layout Soundstage maintains inside Equalizer APO's config directory:
///
/// <code>
/// config.txt                 ← 3-line stub written once at takeover (original backed up)
///     Include: Soundstage\app.txt
/// config\Soundstage\app.txt  ← tiny "switch" file; the only file rewritten for bypass
///     Include: user.txt
///     Include: chain.txt      (omitted while bypassed)
/// config\Soundstage\user.txt ← created once, never rewritten — hand-edit escape hatch
/// config\Soundstage\chain.txt← full generated output (per-device sections)
/// config\Soundstage\backups\ ← timestamped copies
/// config\Soundstage\ir\      ← generated impulse responses (ambience effect)
/// </code>
///
/// Rationale: reverting/uninstalling only requires restoring one small file; bypass writes
/// ~100 bytes (instant, minimal blast radius); Peace or hand edits to config.txt are
/// detectable as lost ownership without content heuristics; user customizations survive
/// every regeneration. APO watches included files, so edits apply live either way.
///
/// Note: paths are joined with backslashes explicitly (not <see cref="Path.Combine"/>)
/// because this code runs on non-Windows test hosts while always describing Windows paths.
/// </summary>
public sealed class ConfigLayout
{
    /// <summary>Marker present in every file Soundstage owns; used for ownership/tamper detection.</summary>
    public const string ManagedMarker = "Managed by Soundstage";

    private const string BypassedStateLine = "# State: BYPASSED";
    private const string ActiveStateLine = "# State: ACTIVE";

    public ConfigLayout(string configDirectory)
    {
        ConfigDirectory = TrimSeparators(configDirectory);
        AppDirectory = Join(ConfigDirectory, CoreInfo.ApoSubdirectoryName);
        ConfigTxtPath = Join(ConfigDirectory, "config.txt");
        SwitchFilePath = Join(AppDirectory, "app.txt");
        UserFilePath = Join(AppDirectory, "user.txt");
        ChainFilePath = Join(AppDirectory, "chain.txt");
        BackupsDirectory = Join(AppDirectory, "backups");
        IrDirectory = Join(AppDirectory, "ir");
    }

    public string ConfigDirectory { get; }

    public string AppDirectory { get; }

    public string ConfigTxtPath { get; }

    public string SwitchFilePath { get; }

    public string UserFilePath { get; }

    public string ChainFilePath { get; }

    public string BackupsDirectory { get; }

    public string IrDirectory { get; }

    /// <summary>The exact content of the config.txt stub Soundstage owns.</summary>
    public string BuildStubContent()
    {
        var doc = new ApoDocument([
            new CommentCommand($"{ManagedMarker}. Do not edit this file — it will be rewritten."),
            new CommentCommand($"Your previous config.txt is preserved under {CoreInfo.ApoSubdirectoryName}\\backups."),
            new CommentCommand($"For custom lines that survive Soundstage updates, edit {CoreInfo.ApoSubdirectoryName}\\user.txt."),
            new IncludeCommand($"{CoreInfo.ApoSubdirectoryName}\\app.txt"),
        ]);
        return doc.Render();
    }

    /// <summary>The switch file content; toggling bypass rewrites only this file.</summary>
    public string BuildSwitchContent(bool bypassed)
    {
        var doc = new ApoDocument();
        doc.Commands.Add(new CommentCommand($"{ManagedMarker}. Processing switch — rewritten on bypass toggle."));
        doc.Commands.Add(new RawCommand(bypassed ? BypassedStateLine : ActiveStateLine));
        doc.Commands.Add(new IncludeCommand("user.txt"));
        if (bypassed)
        {
            doc.Commands.Add(new CommentCommand("Include: chain.txt — disabled while bypassed (A/B comparison)."));
        }
        else
        {
            doc.Commands.Add(new IncludeCommand("chain.txt"));
        }

        return doc.Render();
    }

    /// <summary>Initial content of the never-regenerated user escape-hatch file.</summary>
    public string BuildInitialUserContent()
    {
        var doc = new ApoDocument([
            new CommentCommand("Soundstage user file — yours to edit."),
            new CommentCommand("Lines here run before the generated chain and are never overwritten."),
            new CommentCommand("Equalizer APO syntax reference: https://sourceforge.net/p/equalizerapo/wiki/"),
        ]);
        return doc.Render();
    }

    /// <summary>Placeholder chain content used at takeover before the first real apply.</summary>
    public string BuildEmptyChainContent()
    {
        var doc = new ApoDocument([
            new CommentCommand($"{ManagedMarker}. Generated processing chain — rewritten on every apply."),
            new CommentCommand("No processing configured yet."),
        ]);
        return doc.Render();
    }

    public static bool ContainsManagedMarker(string content) => content.Contains(ManagedMarker, StringComparison.Ordinal);

    public static bool IsSwitchBypassed(string switchContent) => switchContent.Contains(BypassedStateLine, StringComparison.Ordinal);

    private static string Join(params string[] parts) => string.Join('\\', parts);

    private static string TrimSeparators(string path) => path.TrimEnd('\\', '/');
}
